### ISSUE TITLE
Pecl/mcrypt is not compatible with PHP version 7.3.0

### ISSUE THREAD

**Issue by johnnymueller** [mrfoh/docker-laravel#4]
<img width="903" alt="screen shot 2019-01-11 at 3 26 16 pm" src="https://user-images.githubusercontent.com/369241/51417982-09ed9c00-1b3e-11e9-9de3-d03eb29ca985.png">

**Comment by mrfoh** [comment]
Hi @johnnymueller. This [commit](https://github.com/mrfoh/docker-laravel/commit/a34486d8f112c1f9fc53d8c7732090887f736020) fixes the issue
