### ISSUE TITLE
 yaml.scanner.ScannerError: mapping values are not allowed here   in "./docker-compose.yml", line 6, column 10

### ISSUE THREAD

**Issue by Blackbaud-JagjeetChadha** [mrfoh/docker-laravel#5]
Hi,

On running the command "**docker-compose up -d**", I am getting below error:

Error: yaml.scanner.ScannerError: mapping values are not allowed here
  in "./docker-compose.yml", line 6, column 10

Please fine below my docker-compose.yml.

version: ‘3’             
  services:              
    jenkins: 
    image: jenkins/jenkins       
    container_name:  jenkins		    
    ports:           
      - “8080:8080”
    volumes: 
       - “$PWD/Jenkins_home:/var/Jenkins_home” 
	networks: 
		- net
  networks:
   net:
![screenshot#1](https://user-images.githubusercontent.com/22883733/58194538-68d94280-7ce3-11e9-99dc-ce4cc5aa6f47.png)

It seems like issue with port. Please help me with the issue.

**Comment by mrfoh** [comment]
@Blackbaud-JagjeetChadha Hello, from the screenshot of your docker-compose file it seems the problem is an indentation in your yaml file.

**Comment by Blackbaud-JagjeetChadha** [comment]
@mrfoh : Thank you so much for your help. It worked for me. :)

![screenshot#1](https://user-images.githubusercontent.com/22883733/58346829-bc7d9480-7e79-11e9-966f-896412124e06.png)

**Comment by mrfoh** [comment]
@Blackbaud-JagjeetChadha Glad i could help
